title: Nihaal Kuchangi's Portfolio
logo: /assets/img/logo.png
author: Nihaal Kuchangi
description: Showcasing my work on Log Parsers and more.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
